package org.eclipse.scout.contacts.events.shared.location;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.events.client.location.LocationForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class LocationFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public Country getCountry() {
    return getFieldByClass(Country.class);
  }

  /**
   * access method for property LocationId.
   */
  public String getLocationId() {
    return getLocationIdProperty().getValue();
  }

  /**
   * access method for property LocationId.
   */
  public void setLocationId(String locationId) {
    getLocationIdProperty().setValue(locationId);
  }

  public LocationIdProperty getLocationIdProperty() {
    return getPropertyByClass(LocationIdProperty.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public static class City extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Country extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class LocationIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
