package org.eclipse.scout.contacts.events.shared.location;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.events.client.location.LocationTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class LocationTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public LocationTableRowData addRow() {
    return (LocationTableRowData) super.addRow();
  }

  @Override
  public LocationTableRowData addRow(int rowState) {
    return (LocationTableRowData) super.addRow(rowState);
  }

  @Override
  public LocationTableRowData createRow() {
    return new LocationTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return LocationTableRowData.class;
  }

  @Override
  public LocationTableRowData[] getRows() {
    return (LocationTableRowData[]) super.getRows();
  }

  @Override
  public LocationTableRowData rowAt(int index) {
    return (LocationTableRowData) super.rowAt(index);
  }

  public void setRows(LocationTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class LocationTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String locationId = "locationId";
    public static final String name = "name";
    public static final String city = "city";
    public static final String country = "country";
    private String m_locationId;
    private String m_name;
    private String m_city;
    private String m_country;

    public String getLocationId() {
      return m_locationId;
    }

    public void setLocationId(String newLocationId) {
      m_locationId = newLocationId;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public String getCity() {
      return m_city;
    }

    public void setCity(String newCity) {
      m_city = newCity;
    }

    public String getCountry() {
      return m_country;
    }

    public void setCountry(String newCountry) {
      m_country = newCountry;
    }
  }
}
