package org.eclipse.scout.contacts.events.shared.person;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "org.eclipse.scout.contacts.events.client.person.PersonChooserForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PersonChooserFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property EventId.
   */
  public String getEventId() {
    return getEventIdProperty().getValue();
  }

  /**
   * access method for property EventId.
   */
  public void setEventId(String eventId) {
    getEventIdProperty().setValue(eventId);
  }

  public EventIdProperty getEventIdProperty() {
    return getPropertyByClass(EventIdProperty.class);
  }

  public Person getPerson() {
    return getFieldByClass(Person.class);
  }

  public static class EventIdProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Person extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
